<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="LAPTOP-0LBQ9P2B" name="framework.tests.LoginPageTest" tests="5" failures="0" timestamp="2022-04-18T22:20:00 IST" time="0.006" errors="1">
  <testcase name="checkLoginPage" time="0.000" classname="framework.tests.LoginPageTest">
    <skipped/>
  </testcase> <!-- checkLoginPage -->
  <system-out/>
  <testcase name="setUp" time="0.006" classname="framework.tests.LoginPageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at resources.Base.initialiseDriver(Base.java:43)
at framework.tests.LoginPageTest.setUp(LoginPageTest.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:645)
at org.testng.TestRunner.beforeRun(TestRunner.java:634)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <system-out/>
  <testcase name="checkLoginPage" time="0.000" classname="framework.tests.LoginPageTest">
    <skipped/>
  </testcase> <!-- checkLoginPage -->
  <system-out/>
  <testcase name="checkLoginPage" time="0.000" classname="framework.tests.LoginPageTest">
    <skipped/>
  </testcase> <!-- checkLoginPage -->
  <system-out/>
  <testcase name="checkLoginPage" time="0.000" classname="framework.tests.LoginPageTest">
    <skipped/>
  </testcase> <!-- checkLoginPage -->
  <system-out/>
</testsuite> <!-- framework.tests.LoginPageTest -->
